"""F7 — MP Brief: one-page print-styled HTML (browser Save-as-PDF)."""
import html as html_mod

from fastapi import APIRouter, Depends
from fastapi.responses import HTMLResponse
from sqlalchemy import text
from sqlalchemy.orm import Session

from ..db import get_db

router = APIRouter(tags=["brief"])


@router.get("/brief", response_class=HTMLResponse)
def brief(c: str = "south-delhi", db: Session = Depends(get_db)):
    con = db.execute(
        text("SELECT name, state FROM constituencies WHERE code = :c"), {"c": c}
    ).mappings().first() or {"name": "South Delhi", "state": "Delhi"}
    works = db.execute(
        text(
            "SELECT rank, title, ward_code, signal_count, trend_7d, score, "
            "       evidence, justification "
            "FROM demands WHERE rank IS NOT NULL AND constituency = :c "
            "ORDER BY rank LIMIT 10"
        ),
        {"c": c},
    ).mappings().all()
    totals = db.execute(
        text(
            "SELECT (SELECT count(*) FROM demand_signals ds "
            "        JOIN demands d ON d.id = ds.demand_id "
            "        WHERE d.constituency = :c) AS submissions, "
            "       (SELECT count(DISTINCT ds.ward_code) FROM demand_signals ds "
            "        JOIN wards w USING (ward_code) "
            "        WHERE w.constituency = :c) AS wards_heard, "
            "       (SELECT to_char(min(received_at), 'DD Mon YYYY') FROM submissions) AS since"
        ),
        {"c": c},
    ).mappings().one()

    rows = []
    for w in works:
        ev = w["evidence"] or {}
        fact = (ev.get("facts") or ["—"])[0]
        just = (w["justification"] or "").split(". ")[0]
        rows.append(
            "<tr>"
            f"<td class='rank'>#{w['rank']}</td>"
            f"<td><strong>{html_mod.escape(w['title'])}</strong><br>"
            f"<span class='muted'>{html_mod.escape(w['ward_code'] or 'unlocated')} · "
            f"{w['signal_count']} submissions · score {w['score']:.1f}</span><br>"
            f"<span class='muted'>{html_mod.escape(fact)}</span>"
            f"{'<br>' + html_mod.escape(just) + '.' if just else ''}</td>"
            "</tr>"
        )

    body = f"""<!doctype html><html><head><meta charset="utf-8">
<title>sunwai — MP Brief</title>
<style>
  @page {{ size: A4; margin: 14mm; }}
  * {{ margin: 0; box-sizing: border-box; }}
  body {{ font-family: Georgia, 'Times New Roman', serif; color: #111;
         max-width: 720px; margin: 0 auto; padding: 24px; font-size: 13px; }}
  h1 {{ font-size: 21px; margin-bottom: 2px; }}
  .sub {{ color: #444; margin-bottom: 4px; }}
  .totals {{ border-top: 2px solid #111; border-bottom: 1px solid #999;
             padding: 6px 0; margin: 10px 0 14px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td {{ padding: 6px 8px 6px 0; vertical-align: top;
        border-bottom: 1px solid #ddd; }}
  .rank {{ font-weight: bold; white-space: nowrap; width: 34px; }}
  .muted {{ color: #555; }}
  .foot {{ margin-top: 14px; color: #555; font-size: 11px; }}
  .noprint {{ margin: 14px 0; }}
  @media print {{ .noprint {{ display: none; }} body {{ padding: 0; }} }}
</style></head><body>
<div class="noprint"><button onclick="window.print()">Print / Save as PDF</button></div>
<h1>Constituency Development Brief — Top Priority Works</h1>
<div class="sub">{con['name']} Parliamentary Constituency, {con['state']} · generated by sunwai</div>
<div class="totals">
  Based on <strong>{totals['submissions']}</strong> citizen submissions across
  <strong>{totals['wards_heard']}</strong> wards since <strong>{totals['since'] or '—'}</strong>,
  cross-checked with Census 2011 / SEC Delimitation 2022 ward data.
</div>
<table>{''.join(rows) or '<tr><td>No ranked works yet.</td></tr>'}</table>
<div class="foot">
  Ranking: submissions × week-over-week trend × evidence-gap weight (SC share +
  colony-profile deficit). Sources cited per work in the sunwai dashboard.
  Citizen identities are never stored; equity analysis is geographic and Census-based.
</div>
</body></html>"""
    return HTMLResponse(body)
